/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-EricHeikkinen.com-zzUa45TRYnlMaRQTPyd5HX4-laG8a-zD",
  "version": "2020-11-20"
}

export default ebconfig;